// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizTower.IDP.DbContexts;

#nullable disable

namespace QuizTower.IDP.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizTower.IDP.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SecurityCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("SecurityCodeExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Subject")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("Users", "Identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13229d33-99e0-41b3-b18d-4f72127e3971"),
                            Active = true,
                            ConcurrencyStamp = "ceb4f9de-88fa-421a-83bb-e59ae01458f8",
                            Email = "david@someprovider.com",
                            Password = "AQAAAAIAAYagAAAAEAFfhxfb2YqaRx4WePWJMkIE/tmk/oY7csVwmRqu63+TjAVYgulpGORreroxJD1AdA==",
                            SecurityCodeExpirationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subject = "d860efca-22d9-47fd-8249-791ba61b07c7",
                            UserName = "David"
                        },
                        new
                        {
                            Id = new Guid("96053525-f4a5-47ee-855e-0ea77fa6c55a"),
                            Active = true,
                            ConcurrencyStamp = "bd2b6534-5c0e-4a72-ac27-0787d10bf26b",
                            Email = "emma@someprovider.com",
                            Password = "AQAAAAIAAYagAAAAEAFfhxfb2YqaRx4WePWJMkIE/tmk/oY7csVwmRqu63+TjAVYgulpGORreroxJD1AdA==",
                            SecurityCodeExpirationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subject = "b7539694-97e7-4dfe-84da-b4256e1ff5c7",
                            UserName = "Emma"
                        },
                        new
                        {
                            Id = new Guid("a120fd96-1dea-4922-8403-289e5f2dbb6a"),
                            Active = true,
                            ConcurrencyStamp = "7378a412-d481-4da8-ac46-77de95e03859",
                            Email = "admin@admin.com",
                            Password = "AQAAAAIAAYagAAAAEAFfhxfb2YqaRx4WePWJMkIE/tmk/oY7csVwmRqu63+TjAVYgulpGORreroxJD1AdA==",
                            SecurityCodeExpirationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subject = "B8C91EF2-7C41-4561-A323-A73B8F25F686",
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("QuizTower.IDP.Entities.UserClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "Identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44d12e4a-3c29-4200-a341-0923d9c89855"),
                            ConcurrencyStamp = "8647b7ba-c8fc-4a99-8b48-6bab02605b64",
                            Type = "given_name",
                            UserId = new Guid("13229d33-99e0-41b3-b18d-4f72127e3971"),
                            Value = "David"
                        },
                        new
                        {
                            Id = new Guid("b8e60610-32a4-4253-8a4d-b1782a26a160"),
                            ConcurrencyStamp = "f5d27ec9-bc41-4a2c-8ed5-85a5df32f705",
                            Type = "family_name",
                            UserId = new Guid("13229d33-99e0-41b3-b18d-4f72127e3971"),
                            Value = "Flagg"
                        },
                        new
                        {
                            Id = new Guid("7e609aff-85f6-4962-9bfe-3c85d90ecb7c"),
                            ConcurrencyStamp = "cc5e6704-f055-4627-b472-90c547a73c4a",
                            Type = "country",
                            UserId = new Guid("13229d33-99e0-41b3-b18d-4f72127e3971"),
                            Value = "nl"
                        },
                        new
                        {
                            Id = new Guid("148524c2-4095-42e0-917b-33268e7741a6"),
                            ConcurrencyStamp = "6983dfb3-6819-44ea-b659-5ed17f5c9d1d",
                            Type = "role",
                            UserId = new Guid("13229d33-99e0-41b3-b18d-4f72127e3971"),
                            Value = "FreeUser"
                        },
                        new
                        {
                            Id = new Guid("0506f580-6a00-4b7c-a6b7-6fb7acb9077b"),
                            ConcurrencyStamp = "5c6d656b-3ad3-4e0e-9a41-f82d5645644d",
                            Type = "role",
                            UserId = new Guid("13229d33-99e0-41b3-b18d-4f72127e3971"),
                            Value = "Player"
                        },
                        new
                        {
                            Id = new Guid("5b72aed3-1b26-41eb-a5e6-129b75330681"),
                            ConcurrencyStamp = "45ee0fdf-eb4f-4f3a-8c5b-bf11a939cb5a",
                            Type = "given_name",
                            UserId = new Guid("96053525-f4a5-47ee-855e-0ea77fa6c55a"),
                            Value = "Emma"
                        },
                        new
                        {
                            Id = new Guid("c2bd0a20-5d0b-4bff-a4d8-1da5e944d4cc"),
                            ConcurrencyStamp = "6975919b-ded6-4a42-b3b5-c877bfe46b2f",
                            Type = "family_name",
                            UserId = new Guid("96053525-f4a5-47ee-855e-0ea77fa6c55a"),
                            Value = "Flagg"
                        },
                        new
                        {
                            Id = new Guid("1635554c-790f-4b8c-a4ed-def3ee3dbd4e"),
                            ConcurrencyStamp = "d282c098-801d-40a7-bd38-4294bebdf831",
                            Type = "country",
                            UserId = new Guid("96053525-f4a5-47ee-855e-0ea77fa6c55a"),
                            Value = "be"
                        },
                        new
                        {
                            Id = new Guid("3eb4f1d0-a07e-462b-8a8b-aa574e17f3ff"),
                            ConcurrencyStamp = "12a3edfd-7514-4e6c-a1de-e923a7e43677",
                            Type = "role",
                            UserId = new Guid("96053525-f4a5-47ee-855e-0ea77fa6c55a"),
                            Value = "PayingUser"
                        },
                        new
                        {
                            Id = new Guid("0559b1ba-51b5-43c9-a25c-224583e97e38"),
                            ConcurrencyStamp = "75bac4d2-91ee-4d91-bdc7-7a44bacabd85",
                            Type = "role",
                            UserId = new Guid("96053525-f4a5-47ee-855e-0ea77fa6c55a"),
                            Value = "QuizMaster"
                        },
                        new
                        {
                            Id = new Guid("7acce744-a902-4f34-9ab9-92bd6354cc10"),
                            ConcurrencyStamp = "039b49fd-a8a2-4ea2-b5df-2c3fd6a0cad6",
                            Type = "given_name",
                            UserId = new Guid("a120fd96-1dea-4922-8403-289e5f2dbb6a"),
                            Value = "Admin"
                        },
                        new
                        {
                            Id = new Guid("604287f2-e37b-42b2-86a5-291f3b9e50d4"),
                            ConcurrencyStamp = "b98f552e-2db6-45f4-90e5-d73194c157c8",
                            Type = "family_name",
                            UserId = new Guid("a120fd96-1dea-4922-8403-289e5f2dbb6a"),
                            Value = "Flagg"
                        },
                        new
                        {
                            Id = new Guid("7196300d-a1fc-4f03-9508-9a97c26d0dfd"),
                            ConcurrencyStamp = "8a6b5fff-dc5f-46a2-8ef0-a1bccfe59198",
                            Type = "country",
                            UserId = new Guid("a120fd96-1dea-4922-8403-289e5f2dbb6a"),
                            Value = "nl"
                        },
                        new
                        {
                            Id = new Guid("e0a22e93-d8aa-4073-8a92-713ab26b7aa9"),
                            ConcurrencyStamp = "d78bc5bc-a0aa-424a-a23d-8e3f72032444",
                            Type = "role",
                            UserId = new Guid("a120fd96-1dea-4922-8403-289e5f2dbb6a"),
                            Value = "Owner"
                        },
                        new
                        {
                            Id = new Guid("8399b86b-92dd-41c4-9da6-dedb0d6acd93"),
                            ConcurrencyStamp = "86b376b8-577c-4a78-ab2c-cb3acfbba53e",
                            Type = "role",
                            UserId = new Guid("a120fd96-1dea-4922-8403-289e5f2dbb6a"),
                            Value = "SecurityAdmin"
                        });
                });

            modelBuilder.Entity("QuizTower.IDP.Entities.UserLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProviderIdentityKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "Identity");
                });

            modelBuilder.Entity("QuizTower.IDP.Entities.UserSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSecrets", "Identity");
                });

            modelBuilder.Entity("QuizTower.IDP.Entities.UserClaim", b =>
                {
                    b.HasOne("QuizTower.IDP.Entities.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuizTower.IDP.Entities.UserLogin", b =>
                {
                    b.HasOne("QuizTower.IDP.Entities.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuizTower.IDP.Entities.UserSecret", b =>
                {
                    b.HasOne("QuizTower.IDP.Entities.User", "User")
                        .WithMany("Secrets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuizTower.IDP.Entities.User", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Logins");

                    b.Navigation("Secrets");
                });
#pragma warning restore 612, 618
        }
    }
}
